### ISSUE TITLE
get email_address from twitter

### ISSUE THREAD

**Issue by bacancykrina** [GenFirst/react-twitter-auth#14]
Hello, I'm not getting email_address from twitter and those steps in Permission for email access are done. So how can we get using this module?

**Comment by ivanvs** [comment]
Have you checked checkbox on Permission page?

https://cdn-images-1.medium.com/max/800/1*6aRdd2hUqCzS0z20QQk-kA.png

On this picture it is marked in red rectangle and it should be marked, not empty as it is in picture?

Have you done that?

**Comment by bacancykrina** [comment]
Yes. From back-end, we also need to call 'https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true' this api and then only can get the email.
