### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by khteh** [GenFirst/react-twitter-auth#15]
| getRequestToken | @ | react-twitter-auth-component.js:372
-- | -- | -- | --
  | onButtonClick | @ | react-twitter-auth-component.js:356
  | callCallback | @ | react-dom.development.js:542
  | invokeGuardedCallbackDev | @ | react-dom.development.js:581
  | invokeGuardedCallback | @ | react-dom.development.js:438
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:452
  | executeDispatch | @ | react-dom.development.js:836
  | executeDispatchesInOrder | @ | react-dom.development.js:858
  | executeDispatchesAndRelease | @ | react-dom.development.js:956
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.development.js:967
  | forEachAccumulated | @ | react-dom.development.js:935
  | processEventQueue | @ | react-dom.development.js:1112
  | runEventQueueInBatch | @ | react-dom.development.js:3607
  | handleTopLevel | @ | react-dom.development.js:3616
  | handleTopLevelImpl | @ | react-dom.development.js:3347
  | batchedUpdates | @ | react-dom.development.js:11082
  | batchedUpdates | @ | react-dom.development.js:2330
  | dispatchEvent | @ | react-dom.development.js:3421

**Comment by ivanvs** [comment]
Have you enabled CORS? I had similar error until I have enabled CORS.
