### ISSUE TITLE
Opened new window is getting stuck in callback URL

### ISSUE THREAD

**Issue by jaypandya73** [GenFirst/react-twitter-auth#4]
Hi, I am using this npm package to configure Twitter login with Rails api as backend.
Right now I am successfully getting 
```ruby
oauth_token=aZ_IrAAAAAAA1y-RAAABX2KHo6Y&oauth_verifier=Tnd8uWHPZ5jRu5TtORLAK4qKHuEtLjDl
```
with `requestTokenUrl` but after this, request is redirecting to callback URL specified in register twitter application and I am returning json response from there and that new window is showing json response on screen which is obvious because I am returning json response in that action but it is getting stuck there.
what needs to be done in callback URL action so request can process to `loginUrl`?

Help appreciated. Thanks!

**Comment by jaypandya73** [comment]
Okay after a little bit of debugging I see that `polling(popup)` this polling function is being called on the old window instead of new window. that's problem there.

**Comment by MagRelo** [comment]
same issue - did you find a workaround? thanks!

**Comment by jaypandya73** [comment]
@MagRelo - Ohh yes I found that our redirect URL should be one on which our front-end react app is running was facing this issue because it was redirecting to my backend rails-API's host instead of React host.

**Comment by jaypandya73** [comment]
after redirecting to correct callback URL it will work so closing this issue as it has no error. 😄
