### ISSUE TITLE
Feature Request: Option to switch between credentials : same-origin and credentials: include

### ISSUE THREAD

**Issue by henryfailbetter** [GenFirst/react-twitter-auth#5]
Hi GenFirst, 

We are using your TwitterLogin component and it's working great! 

So first of all,  thank you for writing it, and also the incredibly useful Twitter flow for SPA documentation!

We are going to host our API on a different domain to the SPA. The component's http calls are configured to be credentials: same-origin, but we'd need ours to use credentials: include.

Would it be possible to make that an option?

Thanks again, 

Henry

**Comment by ivanvs** [comment]
Hi,

We are very glad to here that you are using the component :+1: 

This sounds as reasonable request. I will add prop to component where you can set up value of credentials header. Default value will still be `same-origin`, but you will be able to change it to `include`.

Is that ok with you?

You can expect that changes tomorrow.

Ivan

**Comment by ivanvs** [comment]
Hi,

I have published new version of library with change that you have requested. Could you please test it and see if that is what you have wanted?

It is v0.0.10

**Comment by henryfailbetter** [comment]
Hi Ivan, wow! thank you for the quick turnaround. We are using the new
version and it works great between our domains now.

Thanks so much!

Henry
