### ISSUE TITLE
Ability to send post variables alongwith requestTokenUrl and loginUrl

### ISSUE THREAD

**Issue by cisprachidubey** [GenFirst/react-twitter-auth#7]
Hello Ivanvs,

I wondering that could we have ability to send some data alongwith requestTokenUrl and loginUrl, In my case i am utilising an API on server side, which checks for some keys which should be posted with the url. If those keys is not present My api is not allowing it to access the method.

**Comment by ivanvs** [comment]
I think that is reasonably request, and so we should add that to library. We will add that as `customHeaders` prop, where every field of json object will be considered as custom header of request.

**Comment by cisprachidubey** [comment]
that will be great :)

**Comment by EfrainTlapale** [comment]
I would like to help with this issue

**Comment by ivanvs** [comment]
That would be great. Create PR and I will review it.

So my main idea was to create new prop, `customHeaders`, where every field of json object will be considered as custom header of request that is being sent to backend application. We don't want to send custom headers to Twitter.

**Comment by ivanvs** [comment]
Implemented with this commit: https://github.com/GenFirst/react-twitter-auth/commit/191d7503bbdbfa759086c69a69f33a53025db019
