### ISSUE TITLE
Auth popup gets blocked by a browser?

### ISSUE THREAD

**Issue by maxkordiyak** [GenFirst/react-twitter-auth#8]
Hi and thanks for this great component! is there a way to make twitter auth work like on https://tweetdeck.twitter.com/ which means user is redirected on an auth page? because a regular popup gets blocked all the time by a browser

**Comment by ivanvs** [comment]
Do you use latest version v0.0.10? That shouldn't happen in latest version.

**Comment by maxkordiyak** [comment]
i've just updated and everything works, thanks
